const http = require('node:http');
const { randomUUID } = require('node:crypto');
const stores = { users:new Map(), customers:new Map(), drivers:new Map(), vehicles:new Map(), trips:new Map(), assignments:new Map(), locations:new Map(), payments:new Map(), ratings:new Map(), notifications:new Map(), audit:[] };
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));}
async function read(req){let raw='';for await(const c of req)raw+=c;try{return raw?JSON.parse(raw):{};}catch{return {};}}
const id=p=>`${p}_${randomUUID().slice(0,8)}`; const path=req=>req.url.split('?')[0].split('/').filter(Boolean);
function start(name,port,handler){http.createServer(async(req,res)=>{try{await handler(req,res,path(req),await read(req));}catch(e){send(res,500,{error:e.message});}}).listen(port,()=>console.log(`${name}: http://localhost:${port}`));}

start('identity-service',3001,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'identity',status:'UP'});if(req.method==='POST'&&p.join('/')==='auth/register'){const u={userId:id('USR'),username:b.username,password:b.password,role:b.role||'CUSTOMER',status:'ACTIVE'};stores.users.set(u.userId,u);return send(res,201,{userId:u.userId,username:u.username,role:u.role});}if(req.method==='POST'&&p.join('/')==='auth/login'){const u=[...stores.users.values()].find(x=>x.username===b.username&&x.password===b.password);if(!u)return send(res,401,{error:'Sai tài khoản hoặc mật khẩu'});return send(res,200,{token:`demo-${u.userId}`,userId:u.userId,role:u.role});}if(req.method==='GET'&&p[0]==='users')return send(res,200,stores.users.get(p[1])||null);send(res,404,{error:'Route not found'});});

start('customer-service',3002,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'customer',status:'UP'});if(req.method==='POST'&&p[0]==='customers'){const x={customerId:id('CUS'),...b};stores.customers.set(x.customerId,x);return send(res,201,x);}if(req.method==='GET'&&p[0]==='customers')return send(res,200,p[1]?stores.customers.get(p[1]):[...stores.customers.values()]);if(req.method==='PUT'&&p[0]==='customers'&&p[1]){const x={...stores.customers.get(p[1]),...b,customerId:p[1]};stores.customers.set(p[1],x);return send(res,200,x);}send(res,404,{error:'Route not found'});});

start('driver-service',3003,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'driver',status:'UP'});if(req.method==='POST'&&p[0]==='drivers'){const x={driverId:id('DRV'),status:'OFFLINE',...b};stores.drivers.set(x.driverId,x);return send(res,201,x);}if(req.method==='GET'&&p[0]==='drivers')return send(res,200,p[1]?stores.drivers.get(p[1]):[...stores.drivers.values()]);if(req.method==='PUT'&&p[0]==='drivers'&&p[1]&&p[2]==='status'){const x=stores.drivers.get(p[1]);if(!x)return send(res,404,{error:'Driver not found'});x.status=b.status;return send(res,200,x);}send(res,404,{error:'Route not found'});});

start('fleet-service',3004,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'fleet',status:'UP'});if(req.method==='POST'&&p[0]==='vehicles'){const x={vehicleId:id('VEH'),...b};stores.vehicles.set(x.vehicleId,x);return send(res,201,x);}if(req.method==='GET'&&p[0]==='vehicles')return send(res,200,p[1]?stores.vehicles.get(p[1]):[...stores.vehicles.values()]);send(res,404,{error:'Route not found'});});

start('trip-service',3005,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'trip',status:'UP'});if(req.method==='POST'&&p[0]==='trips'){if(!b.customerId||!b.pickup||!b.destination||!b.vehicleType)return send(res,400,{error:'customerId, pickup, destination, vehicleType là bắt buộc'});const x={tripId:id('TRIP'),customerId:b.customerId,pickup:b.pickup,destination:b.destination,vehicleType:b.vehicleType,status:'FINDING_DRIVER',driverId:null,createdAt:new Date().toISOString()};stores.trips.set(x.tripId,x);return send(res,201,x);}if(req.method==='GET'&&p[0]==='trips')return send(res,200,p[1]?stores.trips.get(p[1]):[...stores.trips.values()]);if(req.method==='PUT'&&p[0]==='trips'&&p[1]&&p[2]==='status'){const x=stores.trips.get(p[1]);if(!x)return send(res,404,{error:'Trip not found'});x.status=b.status;if(b.driverId)x.driverId=b.driverId;return send(res,200,x);}if(req.method==='PUT'&&p[0]==='trips'&&p[1]&&p[2]==='cancel'){const x=stores.trips.get(p[1]);if(!x)return send(res,404,{error:'Trip not found'});x.status='CANCELLED';return send(res,200,x);}send(res,404,{error:'Route not found'});});

start('dispatch-service',3006,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'dispatch',status:'UP'});if(req.method==='POST'&&p[0]==='dispatch'&&p[1]){const trip=stores.trips.get(p[1]);if(!trip)return send(res,404,{error:'Trip not found'});const available=[...stores.drivers.values()].filter(d=>d.status==='AVAILABLE');if(!available.length)return send(res,200,{tripId:trip.tripId,status:'NO_DRIVER'});const driver=available[0],a={assignmentId:id('ASN'),tripId:trip.tripId,driverId:driver.driverId,status:'PENDING'};stores.assignments.set(a.assignmentId,a);return send(res,201,a);}if(req.method==='POST'&&p[0]==='assignments'&&p[2]==='accept'){const a=stores.assignments.get(p[1]);if(!a)return send(res,404,{error:'Assignment not found'});a.status='ACCEPTED';const d=stores.drivers.get(a.driverId);if(d)d.status='BUSY';const t=stores.trips.get(a.tripId);if(t){t.driverId=a.driverId;t.status='DRIVER_ASSIGNED';}return send(res,200,a);}if(req.method==='POST'&&p[0]==='assignments'&&p[2]==='reject'){const a=stores.assignments.get(p[1]);if(!a)return send(res,404,{error:'Assignment not found'});a.status='REJECTED';return send(res,200,a);}send(res,404,{error:'Route not found'});});

start('location-service',3007,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'location',status:'UP'});if(req.method==='POST'&&p[0]==='locations'){const x={locationId:id('LOC'),...b,time:new Date().toISOString()};stores.locations.set(x.driverId,x);return send(res,201,x);}if(req.method==='GET'&&p[0]==='drivers'&&p[2]==='location')return send(res,200,stores.locations.get(p[1])||null);send(res,404,{error:'Route not found'});});

start('payment-service',3008,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'payment',status:'UP'});if(req.method==='POST'&&p[0]==='payments'){const x={paymentId:id('PAY'),tripId:b.tripId,amount:b.amount,method:b.method||'CASH',status:'SUCCESS',createdAt:new Date().toISOString()};stores.payments.set(x.paymentId,x);return send(res,201,x);}if(req.method==='GET'&&p[0]==='payments')return send(res,200,p[1]?stores.payments.get(p[1]):[...stores.payments.values()]);if(req.method==='POST'&&p[0]==='payments'&&p[2]==='retry'){const x=stores.payments.get(p[1]);if(!x)return send(res,404,{error:'Payment not found'});x.status='SUCCESS';return send(res,200,x);}send(res,404,{error:'Route not found'});});

start('notification-rating-service',3009,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'notification-rating',status:'UP'});if(req.method==='POST'&&p[0]==='notifications'){const x={notificationId:id('NOTI'),status:'SENT',createdAt:new Date().toISOString(),...b};stores.notifications.set(x.notificationId,x);return send(res,201,x);}if(req.method==='POST'&&p[0]==='ratings'){const x={ratingId:id('RAT'),createdAt:new Date().toISOString(),...b};stores.ratings.set(x.ratingId,x);return send(res,201,x);}send(res,404,{error:'Route not found'});});

start('operation-reporting-service',3010,async(req,res,p,b)=>{if(p[0]==='health')return send(res,200,{service:'operation-reporting',status:'UP'});if(req.method==='GET'&&p[0]==='reports'&&p[1]==='summary'){const trips=[...stores.trips.values()],payments=[...stores.payments.values()];return send(res,200,{totalTrips:trips.length,completedTrips:trips.filter(x=>x.status==='COMPLETED').length,cancelledTrips:trips.filter(x=>x.status==='CANCELLED').length,revenue:payments.filter(x=>x.status==='SUCCESS').reduce((s,x)=>s+Number(x.amount||0),0)});}if(req.method==='POST'&&p[0]==='audit'){const x={logId:id('LOG'),time:new Date().toISOString(),...b};stores.audit.push(x);return send(res,201,x);}if(req.method==='GET'&&p[0]==='audit')return send(res,200,stores.audit);send(res,404,{error:'Route not found'});});

console.log('CAB microservices started on ports 3001-3010');
